#!/usr/bin/env python3
"""Write VFX effect templates from a place into a Luau table the headless tests build from.

    python3 tools/export_vfx.py <place.rbxl> tests/sim/vfx_templates.luau Blood BloodHeavy

Each named effect is an Attachment (or a Part, for an effect that emits from a volume) in
ReplicatedStorage.Combat.VFX; every ParticleEmitter in it is written with the properties the effect
code reads (so the tests burst the place's real effects).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rbxl  # noqa: E402
from vfxlib import Lib  # noqa: E402


def num(v):
    return repr(round(float(v), 6))


def main():
    place, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    lib = Lib(place)
    p = lib.place
    lines = ["--!nocheck", "-- GENERATED by tools/export_vfx.py from %s: effects exactly as the place has them, for the tests" % os.path.basename(place), "return {"]
    for name in names:
        ref = p.find("ReplicatedStorage/Combat/VFX/" + name)
        if ref is None:
            raise SystemExit("no effect " + name)
        lines.append("\t%s = {" % name)
        if p.class_name(ref) != "Attachment":
            lines.append("\t\tClass = %r," % p.class_name(ref))
        for k in p.children.get(ref, []):
            if p.class_name(k) != "ParticleEmitter":
                continue
            g = lambda pn: lib.prop(k, pn)  # noqa: E731
            attrs = lib.attrs(k)
            life, speed, spread, acc = g("Lifetime"), g("Speed"), g("SpreadAngle"), g("Acceleration")
            size = ", ".join("{ %s, %s, %s }" % (num(a), num(b), num(c)) for a, b, c in g("Size"))
            lines.append("\t\t{ Name = %r, Texture = %r, Lifetime = { %s, %s }, Speed = { %s, %s }, Size = { %s }, Drag = %s, Acceleration = { %s, %s, %s }, Spread = { %s, %s }, EmissionDirection = %d, Orientation = %d, EmitCount = %s, EmitDelay = %s }," % (
                p.names[k], g("Texture"), num(life[0]), num(life[1]), num(speed[0]), num(speed[1]), size, num(g("Drag")),
                num(acc[0]), num(acc[1]), num(acc[2]), num(spread[0]), num(spread[1]), g("EmissionDirection"), g("Orientation"),
                num(attrs.get("EmitCount", 1)), num(attrs.get("EmitDelay", 0))))
        lines.append("\t},")
    lines.append("}")
    open(out, "w").write("\n".join(lines).replace("'", '"') + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
